# Generated by Django 5.1.1 on 2024-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('postnom', models.CharField(max_length=20)),
                ('matricule', models.CharField(max_length=15)),
                ('state', models.IntegerField(default=0, max_length=1)),
                ('promo', models.CharField(max_length=5)),
            ],
        ),
    ]
