# Generated by Django 5.1.1 on 2024-09-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
